### ISSUE TITLE
asyncio backend sometimes schedules sync tasks on worker threads that are about to shut down

### ISSUE THREAD

**Issue by ntamas** [agronholm/anyio#323]
The `asyncio` backend of AnyIO can sometimes schedule sync tasks on worker threads that have already been designated to shut down.

The erroneous code path is in `anyio._backends._asyncio`, in the `run_sync_in_worker_thread` method. When there are at least two workers in `idle_workers` that have been idle for more than `WorkerThread.MAX_IDLE_TIME`, the code will first pop off one of the workers from `idle_workers` [here](https://github.com/agronholm/anyio/blob/3cada46968b74568190abc71bc4aaf0c535a8c40/src/anyio/_backends/_asyncio.py#L787), and stores it in the `worker` variable. Then, the function goes on to check whether there are any _other_ workers that have been idle long enough. If there is at least one such worker, it will be asked to stop [here](https://github.com/agronholm/anyio/blob/3cada46968b74568190abc71bc4aaf0c535a8c40/src/anyio/_backends/_asyncio.py#L797) -- but the value of the `worker` variable is overwritten in the process, effectively putting the new task in the queue of the already-stopped worker, after the `None` item. The end result is that the worker stops and the future corresponding to the task will never get resolved.

I believe this can be fixed easily by renaming the `worker` variable in [this loop](https://github.com/agronholm/anyio/blob/3cada46968b74568190abc71bc4aaf0c535a8c40/src/anyio/_backends/_asyncio.py#L791), but I haven't had the time to test it yet.

**Comment by ntamas** [comment]
I think the easiest way to reproduce this bug is to spawn a burst of sync tasks on worker threads, followed by a wait that is longer than `WorkerThread.MAX_IDLE_TIME` to ensure that all the worker threads become eligible for reaping. Then, spawn another task, which should then trigger the condition outlined in my first comment.

**Comment by agronholm** [comment]
Good catch, thanks!

**Comment by agronholm** [comment]
I've released v3.2.1 with this fix.

**Comment by ntamas** [comment]
Awesome, thanks for the quick response!

**Comment by jlaine** [comment]
Hi! I think the problem described here still exists despite the fix that was commited. This was discovered while investigating https://github.com/encode/starlette/issues/1248

The following code randomly hangs (if needed raise the number of tasks):

```python
import asyncio
import random
import time

import anyio


def myfunc(*args, **kwargs):
    print("myfunc")
    time.sleep(random.random() * 0.1)


async def myapp():
    await asyncio.sleep(random.random())
    await anyio.to_thread.run_sync(myfunc)
    await asyncio.sleep(random.random())


loop = asyncio.get_event_loop()
tasks = [asyncio.ensure_future(myapp()) for x in range(20)]
loop.run_until_complete(asyncio.gather(*tasks))
```

As far as I can tell there are two odd things here:

- Each WorkerThread is controlled via its `queue`, onto which we queue either a function which needs to be executed or `None` to schedule shutdown. However, when a worker thread is recycled, there is no check whether a `None` (stop) was already queued up. This seems to be the cause of the bug.
- The workers / idle workers are stored in a structure which is local to the event loop, so in effect the worker "pool" is scoped to the event loop. However the lifetime of the worker is bound to a specific `root_task`, since we schedule a call to `.stop()` when the root tasks finishes. When a worker is "recycled" for another task, it will still be stopped when the initial root tasks finishes. This is possibly not a bug, but it's still an odd behaviour.

Here is a patch that adds some debugging lines and highlights the problem:


```patch
--- _asyncio.py.orig    2021-07-22 02:04:03.704713772 +0200
+++ _asyncio.py 2021-07-22 08:50:23.466031253 +0200
@@ -711,6 +711,7 @@
         self.loop = root_task._loop
         self.queue: Queue[Union[Tuple[Callable, tuple, asyncio.Future], None]] = Queue(2)
         self.idle_since = current_time()
+        self.stopping = False

     def _report_result(self, future: asyncio.Future, result: Any,
                        exc: Optional[BaseException]) -> None:
@@ -747,6 +748,8 @@
                 self.queue.task_done()

     def stop(self, f: Optional[asyncio.Task] = None) -> None:
+        print("thread %x stop scheduled" % id(self))
+        self.stopping = True
         self.queue.put_nowait(None)
         self.workers.discard(self)
         try:
@@ -796,6 +799,7 @@
                     expired_worker.root_task.remove_done_callback(expired_worker.stop)
                     expired_worker.stop()

+            print("thread %x queueing func (stopping: %s)" % (id(worker), worker.stopping))
             worker.queue.put_nowait((func, args, future))
             return await future
```

In the cases when the script I provided hangs, we can see:

```thread 7f9c2e65b1c0 stop scheduled
thread 7f9c2e65b1c0 queueing func (stopping: True)```

=> this is not going to complete

**Comment by uSpike** [comment]
@jlaine I think your example code is fixed if you use `asyncio.run()` instead of `loop.run_until_complete()`.

```python
import asyncio
import random
import time

import anyio


def myfunc(*args, **kwargs):
    print("myfunc")
    time.sleep(random.random() * 0.1)


async def myapp():
    await asyncio.sleep(random.random())
    await anyio.to_thread.run_sync(myfunc)
    await asyncio.sleep(random.random())


async def main():
    tasks = [asyncio.ensure_future(myapp()) for x in range(100)]
    await asyncio.gather(*tasks)

asyncio.run(main())
```
`loop.run_until_complete()` does not ensure that everything is cleaned up properly.  `asyncio.run` (or even better, `anyio.run()`) is much preferred.

**Comment by agronholm** [comment]
@jlaine I will get this sorted by the next release (due soon).

@uSpike Not using `run_until_complete()` is impractical in many circumstances (anyio's pytest plugin uses it too).

**Comment by smurfix** [comment]
While you *can* convince asyncio to properly shut down its loop, looking at `asyncio.run` it's obvious that the process is sufficiently nontrivial (cf. `asyncio/runners.py`) so that, well, using `run_until_complete()` for non-trivial programs doesn't seem like a particularly good idea.

**Comment by agronholm** [comment]
Yet it is the only choice in certain environments that weren't designed for async in mind from the ground up.

**Comment by jlaine** [comment]
@uSpike my example was specifically designed to highlight the behaviour when you have multiple "root tasks". This can be the case for instance if you are using asyncio's Protocol classes and kicking off tasks in response to data received from the network.

Your suggestion will not *fix* the issue (there really is an issue with how workers are shutdown when a task completes, and it's not due to how the event loop shuts down), but it will work around it because all the threading work will belong to the same "root task".

@agronholm thanks, feel free to use or throw away my PR #346 as you see fit. In any case I'd be happy to try out whatever solution you decide is best.

**Comment by agronholm** [comment]
Building a reliable regression test seems to be the biggest challenge here.

**Comment by jlaine** [comment]
Thanks @agronholm !
