### ISSUE TITLE
3.6.1: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [agronholm/anyio#442]
On building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.
Here is the output with warnings:
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.1
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
making output directory... done
WARNING: html_static_path entry '_static' does not exist
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 19 added, 0 changed, 0 removed
reading sources... [100%] versionhistory
WARNING: Failed guarded type import with ModuleNotFoundError("No module named '_typeshed'")
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-anyiodoc.3 { basics tasks cancellation synchronization streams typedattrs networking threads subprocesses fileio signals testing api migration faq support contributing versionhistory } /home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/cancellation.rst:30: WARNING: py:attr reference target not found: abc.CancelScope.deadline
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/networking.rst:110: WARNING: py:func reference target not found: socket.socket
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/threads.rst:85: WARNING: py:func reference target not found: start_blocking_portal
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/fileio.rst:56: WARNING: py:meth reference target not found: pathlib.Path.read_bytes`
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/signals.rst:28: WARNING: py:func reference target not found: start_blocking_portal
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.current_time:3: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitableFloat
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.TypedAttributeProvider.extra_attributes:: WARNING: py:class reference target not found: anyio._core._typedattr.T_Attr
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.TypedAttributeProvider.extra_attributes:: WARNING: py:class reference target not found: anyio._core._typedattr.T_Attr
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.fail_after:9: WARNING: py:class reference target not found: anyio.abc.CancelScope
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.CancelScope:1: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAsyncContextManager
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._tasks.CancelScope.cancel:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.call:: WARNING: py:class reference target not found: anyio.from_thread.T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.call:: WARNING: py:class reference target not found: anyio.from_thread.T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.call:: WARNING: py:class reference target not found: anyio.from_thread.T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.call:: WARNING: py:class reference target not found: anyio.from_thread.T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.spawn_task:: WARNING: py:class reference target not found: anyio.from_thread.T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.spawn_task:: WARNING: py:class reference target not found: Future
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.spawn_task:: WARNING: py:class reference target not found: T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.spawn_task:: WARNING: py:class reference target not found: anyio.from_thread.T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.spawn_task:: WARNING: py:class reference target not found: Future
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.spawn_task:: WARNING: py:class reference target not found: T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.start_task_soon:: WARNING: py:class reference target not found: anyio.from_thread.T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.start_task_soon:: WARNING: py:class reference target not found: Future
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.start_task_soon:: WARNING: py:class reference target not found: T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.start_task_soon:: WARNING: py:class reference target not found: anyio.from_thread.T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.start_task_soon:: WARNING: py:class reference target not found: Future
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.start_task_soon:: WARNING: py:class reference target not found: T_Retval
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.wrap_async_context_manager:6: WARNING: py:class reference target not found: typing.AbstractAsyncContextManager
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.wrap_async_context_manager:8: WARNING: py:class reference target not found: typing.AbstractContextManager
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.wrap_file:5: WARNING: py:class reference target not found: anyio._core._fileio.AsyncFile
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.Path:11: WARNING: py:meth reference target not found: pathlib.Path.absolute
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectSendStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectSendStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.Listener:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Stream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/file.py:docstring of anyio.streams.file.FileReadStream:1: WARNING: py:class reference target not found: anyio.streams.file._BaseFileStream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/file.py:docstring of anyio.streams.file.FileWriteStream:1: WARNING: py:class reference target not found: anyio.streams.file._BaseFileStream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectSendStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectSendStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectSendStream.send_nowait:13: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.MultiListener:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Stream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.MultiListener:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Stream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.MultiListener:: WARNING: py:class reference target not found: T_Stream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.StapledObjectStream:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.StapledObjectStream:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/text.py:docstring of anyio.streams.text.TextReceiveStream:6: WARNING: py:class reference target not found: anyio.abc._streams.ObjectReceiveStream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/text.py:docstring of anyio.streams.text.TextReceiveStream:8: WARNING: py:class reference target not found: dataclasses.InitVar
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/text.py:docstring of anyio.streams.text.TextReceiveStream:11: WARNING: py:class reference target not found: dataclasses.InitVar
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/text.py:docstring of anyio.streams.text.TextSendStream:: WARNING: py:class reference target not found: AnyByteSendStream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/text.py:docstring of anyio.streams.text.TextStream:: WARNING: py:class reference target not found: AnyByteStream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/tls.py:docstring of anyio.streams.tls.TLSStream:: WARNING: py:class reference target not found: AnyByteStream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/tls.py:docstring of anyio.streams.tls.TLSStream.unwrap:3: WARNING: py:class reference target not found: anyio.abc._streams.ObjectStream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/tls.py:docstring of anyio.streams.tls.TLSStream.wrap:5: WARNING: py:class reference target not found: anyio.abc._streams.ObjectStream
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/streams/tls.py:docstring of anyio.streams.tls.TLSListener:4: WARNING: py:meth reference target not found: handle_handshake_error
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.getaddrinfo:13: WARNING: py:class reference target not found: socket.AddressFamily
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.getaddrinfo:15: WARNING: py:class reference target not found: socket.SocketKind
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.getaddrinfo:21: WARNING: py:class reference target not found: socket.AddressFamily
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.getaddrinfo:21: WARNING: py:class reference target not found: socket.SocketKind
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.SocketStream:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.SocketListener:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.UDPSocket:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc.ConnectedUDPSocket:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/abc/__init__.py:docstring of anyio.abc._subprocesses.Process.send_signal:5: WARNING: py:class reference target not found: signal.Signals
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.Event.set:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.Lock.acquire_nowait:: WARNING: py:exc reference target not found: ~WouldBlock
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.Lock.release:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.Condition.acquire_nowait:: WARNING: py:exc reference target not found: ~WouldBlock
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.Condition.release:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.Semaphore.acquire_nowait:: WARNING: py:exc reference target not found: ~WouldBlock
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.Semaphore.release:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.Semaphore.statistics:6: WARNING: py:class reference target not found: anyio.SemaphoreStatistics
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.CapacityLimiter.acquire_nowait:7: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio._core._synchronization.CapacityLimiter.acquire_on_behalf_of_nowait:9: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.open_signal_receiver:5: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAsyncContextManager
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/lowlevel.py:docstring of anyio.lowlevel.RunVar:1: WARNING: py:obj reference target not found: anyio.lowlevel.T
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.maybe_async_cm:6: WARNING: py:class reference target not found: typing.AbstractContextManager
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.maybe_async_cm:6: WARNING: py:class reference target not found: typing.AbstractAsyncContextManager
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.maybe_async_cm:8: WARNING: py:class reference target not found: typing.AbstractAsyncContextManager
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/src/anyio/__init__.py:docstring of anyio.get_running_tasks:3: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitableList
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/migration.rst:22: WARNING: py:meth reference target not found: abc.CancelScope.cancel
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/migration.rst:87: WARNING: py:meth reference target not found: TaskGroup.spawn
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/migration.rst:87: WARNING: py:meth reference target not found: TaskGroup.start_soon
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/migration.rst:91: WARNING: py:meth reference target not found: TaskGroup.spawn
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/migration.rst:112: WARNING: py:meth reference target not found: TaskGroup.spawn
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/migration.rst:112: WARNING: py:meth reference target not found: BlockingPortal.spawn_task
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/migration.rst:112: WARNING: py:meth reference target not found: BlockingPortal.start_task_soon
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/migration.rst:115: WARNING: py:func reference target not found: create_blocking_portal
/home/tkloczko/rpmbuild/BUILD/anyio-3.6.1/docs/migration.rst:115: WARNING: py:class reference target not found: BlockingPortal
done
build succeeded, 99 warnings.
```
</details>

You can peak on fixes that kind of issues in other projects
https://github.com/latchset/jwcrypto/pull/289
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/latchset/jwcrypto/pull/289
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/sissaschool/elementpath/commit/bf869d9e

**Comment by agronholm** [comment]
All of the Sphinx build warnings have been fixed, as of 79d5cc66.

**Comment by kloczek** [comment]
Just tested 3.7.0 and I still see warnings
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.2.1
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 19 added, 0 changed, 0 removed
reading sources... [100%] versionhistory
/usr/lib/python3.8/site-packages/anyio/lowlevel.py:docstring of anyio.lowlevel.checkpoint:7: WARNING: Literal block ends without a blank line; unexpected unindent.
/usr/lib/python3.8/site-packages/anyio/lowlevel.py:docstring of anyio.lowlevel.cancel_shielded_checkpoint:7: WARNING: Literal block ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-anyiodoc.3 { basics tasks cancellation synchronization streams typedattrs networking threads subprocesses fileio signals testing api migration faq support contributing versionhistory } /home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/cancellation.rst:30: WARNING: py:attr reference target not found: abc.CancelScope.deadline
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/networking.rst:110: WARNING: py:func reference target not found: socket.socket
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/threads.rst:85: WARNING: py:func reference target not found: start_blocking_portal
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/threads.rst:195: WARNING: py:func reference target not found: to_thread.run
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/fileio.rst:56: WARNING: py:meth reference target not found: pathlib.Path.read_bytes`
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/signals.rst:28: WARNING: py:func reference target not found: start_blocking_portal
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.current_time:3: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitableFloat
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.TypedAttributeProvider.extra_attributes:1: WARNING: py:class reference target not found: anyio._core._typedattr.T_Attr
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.TypedAttributeProvider.extra_attributes:1: WARNING: py:class reference target not found: anyio._core._typedattr.T_Attr
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.fail_after:9: WARNING: py:class reference target not found: anyio.abc.CancelScope
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.CancelScope:1: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAsyncContextManager
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._tasks.CancelScope.cancel:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/usr/lib/python3.8/site-packages/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.wrap_async_context_manager:6: WARNING: py:class reference target not found: typing.AbstractAsyncContextManager
/usr/lib/python3.8/site-packages/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.wrap_async_context_manager:8: WARNING: py:class reference target not found: typing.AbstractContextManager
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.wrap_file:5: WARNING: py:class reference target not found: anyio._core._fileio.AsyncFile
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectSendStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.ObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.ObjectSendStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.ObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.ObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.ObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.Listener:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Stream
/usr/lib/python3.8/site-packages/anyio/streams/file.py:docstring of anyio.streams.file.FileReadStream:1: WARNING: py:class reference target not found: anyio.streams.file._BaseFileStream
/usr/lib/python3.8/site-packages/anyio/streams/file.py:docstring of anyio.streams.file.FileWriteStream:1: WARNING: py:class reference target not found: anyio.streams.file._BaseFileStream
/usr/lib/python3.8/site-packages/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_Item
/usr/lib/python3.8/site-packages/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_Item
/usr/lib/python3.8/site-packages/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectSendStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_Item
/usr/lib/python3.8/site-packages/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectSendStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_Item
/usr/lib/python3.8/site-packages/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectSendStream.send_nowait:12: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/usr/lib/python3.8/site-packages/anyio/streams/stapled.py:docstring of anyio.streams.stapled.MultiListener:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Stream
/usr/lib/python3.8/site-packages/anyio/streams/stapled.py:docstring of anyio.streams.stapled.MultiListener:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Stream
/usr/lib/python3.8/site-packages/anyio/streams/stapled.py:docstring of anyio.streams.stapled.MultiListener:1: WARNING: py:class reference target not found: T_Stream
/usr/lib/python3.8/site-packages/anyio/streams/stapled.py:docstring of anyio.streams.stapled.StapledObjectStream:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Item
/usr/lib/python3.8/site-packages/anyio/streams/stapled.py:docstring of anyio.streams.stapled.StapledObjectStream:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Item
/usr/lib/python3.8/site-packages/anyio/streams/text.py:docstring of anyio.streams.text.TextReceiveStream:6: WARNING: py:class reference target not found: anyio.abc._streams.ObjectReceiveStream
/usr/lib/python3.8/site-packages/anyio/streams/text.py:docstring of anyio.streams.text.TextReceiveStream:8: WARNING: py:class reference target not found: dataclasses.InitVar
/usr/lib/python3.8/site-packages/anyio/streams/text.py:docstring of anyio.streams.text.TextReceiveStream:11: WARNING: py:class reference target not found: dataclasses.InitVar
/usr/lib/python3.8/site-packages/anyio/streams/text.py:docstring of anyio.streams.text.TextSendStream:1: WARNING: py:class reference target not found: AnyByteSendStream
/usr/lib/python3.8/site-packages/anyio/streams/text.py:docstring of anyio.streams.text.TextStream:1: WARNING: py:class reference target not found: AnyByteStream
/usr/lib/python3.8/site-packages/anyio/streams/tls.py:docstring of anyio.streams.tls.TLSStream:1: WARNING: py:class reference target not found: AnyByteStream
/usr/lib/python3.8/site-packages/anyio/streams/tls.py:docstring of anyio.streams.tls.TLSStream.unwrap:3: WARNING: py:class reference target not found: anyio.abc._streams.ObjectStream
/usr/lib/python3.8/site-packages/anyio/streams/tls.py:docstring of anyio.streams.tls.TLSStream.wrap:5: WARNING: py:class reference target not found: anyio.abc._streams.ObjectStream
/usr/lib/python3.8/site-packages/anyio/streams/tls.py:docstring of anyio.streams.tls.TLSListener:4: WARNING: py:meth reference target not found: handle_handshake_error
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.getaddrinfo:13: WARNING: py:class reference target not found: socket.AddressFamily
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.getaddrinfo:15: WARNING: py:class reference target not found: socket.SocketKind
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.getaddrinfo:21: WARNING: py:class reference target not found: socket.AddressFamily
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.getaddrinfo:21: WARNING: py:class reference target not found: socket.SocketKind
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.SocketStream:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.SocketListener:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.UDPSocket:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/usr/lib/python3.8/site-packages/anyio/abc/__init__.py:docstring of anyio.abc.ConnectedUDPSocket:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.Event.set:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.Lock.acquire_nowait:1: WARNING: py:exc reference target not found: ~WouldBlock
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.Lock.release:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.Condition.acquire_nowait:1: WARNING: py:exc reference target not found: ~WouldBlock
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.Condition.release:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.Semaphore.acquire_nowait:1: WARNING: py:exc reference target not found: ~WouldBlock
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.Semaphore.release:4: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.Semaphore.statistics:1: WARNING: py:class reference target not found: anyio.SemaphoreStatistics
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.CapacityLimiter.acquire_nowait:7: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio._core._synchronization.CapacityLimiter.acquire_on_behalf_of_nowait:8: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitable
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.open_signal_receiver:5: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAsyncContextManager
/usr/lib/python3.8/site-packages/anyio/lowlevel.py:docstring of anyio.lowlevel.RunVar:1: WARNING: py:obj reference target not found: anyio.lowlevel.T
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.maybe_async_cm:6: WARNING: py:class reference target not found: typing.AbstractContextManager
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.maybe_async_cm:6: WARNING: py:class reference target not found: typing.AbstractAsyncContextManager
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.maybe_async_cm:8: WARNING: py:class reference target not found: typing.AbstractAsyncContextManager
/usr/lib/python3.8/site-packages/anyio/__init__.py:docstring of anyio.get_running_tasks:3: WARNING: py:class reference target not found: anyio._core._compat.DeprecatedAwaitableList
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/migration.rst:22: WARNING: py:meth reference target not found: abc.CancelScope.cancel
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/migration.rst:87: WARNING: py:meth reference target not found: TaskGroup.spawn
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/migration.rst:87: WARNING: py:meth reference target not found: TaskGroup.start_soon
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/migration.rst:91: WARNING: py:meth reference target not found: TaskGroup.spawn
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/migration.rst:112: WARNING: py:meth reference target not found: TaskGroup.spawn
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/migration.rst:112: WARNING: py:meth reference target not found: BlockingPortal.spawn_task
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/migration.rst:112: WARNING: py:meth reference target not found: BlockingPortal.start_task_soon
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/migration.rst:115: WARNING: py:func reference target not found: create_blocking_portal
/home/tkloczko/rpmbuild/BUILD/anyio-3.7.0/docs/migration.rst:115: WARNING: py:class reference target not found: BlockingPortal
done
build succeeded, 81 warnings.
```
</details>

**Comment by agronholm** [comment]
Yeah, I realized my docs build didn't have `-n` enabled, although `-W` was. I could've sworn I had dealt with these already.

**Comment by agronholm** [comment]
Is this blocking your builds?

**Comment by agronholm** [comment]
> Currently I'm not able to test that fix because it cannot be applied directly on top of last release.

What fix are you referring to?

**Comment by kloczek** [comment]
> What fix are you referring to?

79d5cc66
That commit cannot be applied directly on top of last release.
Will test that and give you shout when it will be released new version.

**Comment by agronholm** [comment]
With `-W`, the docs build completes fine as of v3.7.0. But if you add the `-n` flag, then it fails.

**Comment by agronholm** [comment]
The biggest issue for me right now is figuring out how to silence the warnings about the type variables not being found.

**Comment by agronholm** [comment]
These are the problems that are left after the fixes I just pushed (cd432900):

- I don't know how to silence warnings about missing references to type variables
- I don't know how to omit undocumented intermediate classes from the list of bases
- I don't know what to do about references to `socket.AddressFamily` or `socket.SocketKind`, neither of which have Sphinx nodes to reference

**Comment by kloczek** [comment]
Just tested 4.0.0 and I still see nitpick warnings
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.1.2
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 19 added, 0 changed, 0 removed
reading sources... [100%] versionhistory
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-anyiodoc.3 { basics tasks cancellation synchronization streams typedattrs networking threads subprocesses fileio signals testing api migration faq support contributing versionhistory } /home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/__init__.py:docstring of anyio.TypedAttributeProvider.extra_attributes:1: WARNING: py:class reference target not found: T_Attr
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/__init__.py:docstring of anyio.TypedAttributeProvider.extra_attributes:1: WARNING: py:class reference target not found: T_Attr
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.TaskStatus:1: WARNING: py:obj reference target not found: anyio.abc._tasks.T_contra
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/from_thread.py:docstring of anyio.from_thread.BlockingPortal.start_task_soon:1: WARNING: py:class reference target not found: T_Retval
<unknown>:1: WARNING: py:class reference target not found: typing.AbstractAsyncContextManager
<unknown>:1: WARNING: py:class reference target not found: typing.AbstractContextManager
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/__init__.py:docstring of anyio.Path:7: WARNING: py:meth reference target not found: pathlib.Path.link_to
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/__init__.py:docstring of anyio.create_memory_object_stream:1: WARNING: py:class reference target not found: T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/__init__.py:docstring of anyio.create_memory_object_stream:1: WARNING: py:class reference target not found: T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/__init__.py:docstring of anyio.create_memory_object_stream:3: WARNING: py:func reference target not found: create_memory_object_stream[T_Item]
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_co
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectSendStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_contra
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.UnreliableObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_co
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectSendStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_contra
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.ObjectStream:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.Listener:1: WARNING: py:obj reference target not found: anyio.abc._streams.T_co
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/file.py:docstring of anyio.streams.file.FileReadStream:1: WARNING: py:class reference target not found: anyio.streams.file._BaseFileStream
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/file.py:docstring of anyio.streams.file.FileWriteStream:1: WARNING: py:class reference target not found: anyio.streams.file._BaseFileStream
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_co
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectReceiveStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_co
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectSendStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_contra
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/memory.py:docstring of anyio.streams.memory.MemoryObjectSendStream:1: WARNING: py:obj reference target not found: anyio.streams.memory.T_contra
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.MultiListener:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Stream
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.MultiListener:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Stream
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.MultiListener:1: WARNING: py:class reference target not found: T_Stream
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.StapledObjectStream:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/stapled.py:docstring of anyio.streams.stapled.StapledObjectStream:1: WARNING: py:obj reference target not found: anyio.streams.stapled.T_Item
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/text.py:docstring of anyio.streams.text.TextSendStream:1: WARNING: py:class reference target not found: AnyByteSendStream
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/text.py:docstring of anyio.streams.text.TextStream:1: WARNING: py:class reference target not found: AnyByteStream
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/streams/tls.py:docstring of anyio.streams.tls.TLSStream:1: WARNING: py:class reference target not found: AnyByteStream
<unknown>:1: WARNING: py:class reference target not found: anyio.abc._streams.ObjectStream
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.SocketStream:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.SocketListener:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.UDPSocket:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/abc/__init__.py:docstring of anyio.abc.ConnectedUDPSocket:1: WARNING: py:class reference target not found: anyio.abc._sockets._SocketProvider
/home/tkloczko/rpmbuild/BUILD/anyio-4.0.0/src/anyio/lowlevel.py:docstring of anyio.lowlevel.RunVar:1: WARNING: py:obj reference target not found: anyio.lowlevel.T
done
build succeeded, 40 warnings.
```
</details>

**Comment by agronholm** [comment]
I've fixed what I can and I have no clue what to do about the rest.

**Comment by kloczek** [comment]
OK I understand. Here is list of links with updated similar issues
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/frostming/unearth/issues/14
https://github.com/jaraco/cssutils/issues/21
https://github.com/latchset/jwcrypto/pull/289
https://github.com/latchset/jwcrypto/pull/289
https://github.com/pypa/distlib/commit/98b9b89f
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/sqlalchemy/sqlalchemy/commit/5e88e6e8
